Need to specify relative or absolute path to the volumes
If we don't add $PWD/ or ./, then it complains:
ERROR: for candidate  Cannot create container for service candidate: create flavors/candidate: "flavors/candidate" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed
ERROR: Encountered errors while bringing up the project.